# Generated by Django 4.2.7 on 2023-12-01 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_choice_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="timestamp",
        ),
    ]
