# Generated by Django 4.2.7 on 2023-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_remove_choice_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_category", models.CharField(max_length=255)),
                ("csv_question", models.CharField(max_length=255)),
            ],
        ),
    ]
