# Generated by Django 4.2.7 on 2023-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_csvdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="csv_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
