# Generated by Django 4.2.7 on 2023-12-01 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_csvdata_csv_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvdata",
            old_name="csv_category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="csvdata",
            old_name="csv_code",
            new_name="CategoryCode",
        ),
        migrations.RenameField(
            model_name="csvdata",
            old_name="csv_question",
            new_name="Question",
        ),
    ]
