# Generated by Django 4.2.7 on 2023-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_rename_csv_category_csvdata_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvdata",
            old_name="Category",
            new_name="csv_category",
        ),
        migrations.RenameField(
            model_name="csvdata",
            old_name="CategoryCode",
            new_name="csv_code",
        ),
        migrations.RenameField(
            model_name="csvdata",
            old_name="Question",
            new_name="csv_question",
        ),
    ]
