# Generated by Django 4.2.7 on 2023-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_rename_category_csvdata_csv_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_series", models.CharField(max_length=255)),
                ("csv_subject", models.CharField(max_length=512)),
                ("csv_career", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="question_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
